# Write docker-compose file here
# For instructions, see https://github.com/SnowSuno/wheel-assignment-solution#2-docker-composeyml-%EC%9E%91%EC%84%B1
version: "3"
services:
  mongodb:
    container_name: taxi-mongo
    image: mongo:5.0.8
    restart: always
    ports:
      - 27017:27017
    volumes:
      - taxi-mongo-db:/data/db:rw

volumes:
  taxi-mongo-db:
