# Write github action workflow here
# For instructions, see https://github.com/SnowSuno/wheel-assignment-solution#3-cicd-%ED%8C%8C%EC%9D%B4%ED%94%84%EB%9D%BC%EC%9D%B8-%EA%B5%AC%EC%84%B1
name: cd_images

# 태그 생성 시 실행
on:
  release:
    types: [created]
  push:
    branches: ["main"]

jobs:
  build_images:
    name: Build images and push to image registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get tag version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push taxi-back
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/taxi-back:latest
            ghcr.io/${{ github.repository_owner }}/taxi-back:${{ env.RELEASE_VERSION }}

      - name: Build and push taxi-front
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/taxi-front:latest
            ghcr.io/${{ github.repository_owner }}/taxi-front:${{ env.RELEASE_VERSION }}
